Snaipe/Criterion

- src/event.c
If `fread()` returns `0` the allocated memory is leaked.
> Possible leak fixed

- CMakeLists.txt
- src/compat/mockfile.c
* Also adds a search path `/usr/local/include` to top-level CMakeLists.
Fixes #48.
> Build: Improves preprocessor directives for BSD

- include/criterion/criterion.h
- src/runner.c
- src/runner.h
I am able to reproduce this on my windows 10 setup.
Basically, this has to to with how the linker aligns the section entries and coalesce each section from all the compilation units into one.
This is pretty much a show stopper for any one having this issue.
> Sometimes tests from only one compilation unit are registered

- doc/index.rst
- doc/parameterized.rst
- include/criterion/criterion.h
- include/criterion/parameterized.h
- include/criterion/types.h
- samples/CMakeLists.txt
- samples/outputs/parameterized.c.bin.err.expected
- samples/parameterized.c
- src/compat/process.c
- src/compat/process.h
- src/core/runner.c
- src/core/worker.c
- src/core/worker.h
From the original issue (#43):
From the discussion at https://github.com/Snaipe/Criterion/issues/40, a use-case has come to light:
>  [...] to implement parameterized tests, that would iterate over a user-generated dataset rather than the cartesian product of many datasets.
Also, this will run a separate test for each member of dataset and hence yield better result stats.
e.g. current approach is to enumerate over `TheoryDataSet` placeholder data array, which results in:
>
[====] Synthesis: Tested: 1 | Passing: 0 | Failing: 1 | Crashing: 0
for 1276 data items tested out of which (for example) only 26 are failing. 
With `ParameterizedTest` feature, we expect to get:
>
[====] Synthesis: Tested: 1276 | Passing: 1250 | Failing: 26 | Crashing: 0
> Add parameterized tests

- dependencies/valgrind/include/valgrind/valgrind.h
Clang on FreeBSD was complaining:
```csh
[ 26%] Building C object CMakeFiles/criterion.dir/src/core/abort.c.o
[ 30%] Building C object CMakeFiles/criterion.dir/src/core/report.c.o
[ 30%] Building C object CMakeFiles/criterion.dir/src/core/runner.c.o
In file included from /root/projects/Criterion/Criterion/Criterion/src/core/runner.c:29:
/root/projects/Criterion/Criterion/Criterion/dependencies/valgrind/include/valgrind/valgrind.h:6223:29: error: unused
parameter 'format' [-Werror,-Wunused-parameter]
VALGRIND_PRINTF(const char *format, ...)
^
/root/projects/Criterion/Criterion/Criterion/dependencies/valgrind/include/valgrind/valgrind.h:6261:39: error: unused
parameter 'format' [-Werror,-Wunused-parameter]
VALGRIND_PRINTF_BACKTRACE(const char *format, ...)
^
2 errors generated.
```
The …
> Deps: Mark UNUSED parameters in valgrind header

- CMakeLists.txt
- include/criterion/criterion.h
- include/criterion/logging.h
- include/criterion/types.h
- po/fr.po
- samples/tests/CMakeLists.txt
- samples/tests/exception.cc
- src/compat/internal.h
- src/compat/posix.h
- src/core/abort.c
- src/core/abort.h
- src/core/report.h
- src/core/runner.c
- src/core/worker.h
- src/core/wrappers/wrap.c
- src/core/wrappers/wrap.cc
- src/core/wrappers/wrap.h
- src/io/event.c
- src/io/event.h
- src/log/normal.c
Currently the test function is executed straight from the C worker code. This means that escaping the context using a language feature that does not come from C (C++ exceptions come to mind) induces undefined behaviour.
A solution would be to include a `criterion_test_language` enum containing `CR_LANG_C` and `CR_LANG_CPP` and add a field of this enum type in the test metadata. Then, depending on the value of this field, the C worker would call the proper "wrapper" function written in the target language.
The wrappers would look something like this:
```c
// C wrapper
void wrapper_c(struct criterion_test *test) {
test->test();
}
```
```c++
// C++ wrapper
void wrapper_cpp(criterion_test *test) {
try {
test->test()
} catch (const std::exception &ex) {
cr_assert_abort("Caught an unexpected …
```
> Tests does not provide language containment

- .cmake/Modules/Capabilities.cmake
- CMakeLists.txt
- include/criterion/common.h
- src/config.h.in
- src/log/normal.c
- src/log/tap.c
Also cleans up redundancies and adds pragma in `UNUSED` macro.
> config: Check strtok_s capability

- CMakeLists.txt
Shared libraries should have an SONAME
to facilitate proper dynamic linking.
@Snaipe it would be nice for the criterion shared library to have 
a proper SONAME.  
Signed-off-by: Howard Pritchard <howardp@lanl.gov>
> cmake: add a SOVERSION to libcriterion.so

- doc/assert.rst
Size parameter was missing from `cr_assert_arr_eq` and `cr_assert_arr_neq`.
> Fixed doc/assert: missing size parameter

- include/criterion/theories.h
added doxygen comments for cr_assume macros and grouped them
disabled REPEAT_BRIEF, enabled JAVADOC_AUTOBRIEF @ doxyfile
used the same Argument names as for cr_assert (i.e. Reference, Expected, Unexpected)
> added doxygen for cr_assume_* macros

- doc/faq.rst
First of all, thank you for this terrific project.
I was trying to determine why my tests weren't generating any coverage data, and I found the answer [here](https://github.com/Snaipe/Criterion/pull/84). I didn't see this information anywhere in the official docs, so I added your response to the FAQs in this commit.
> Add coverage info to FAQ in docs

- doc/Doxyfile
- doc/_static/style.css
- doc/_templates/page.html
- doc/assert.rst
- doc/conf.py
- doc/parameterized.rst
- doc/requirements.txt
- doc/starter.rst
- doc/theories.rst
- include/criterion/assert.h
- include/criterion/criterion.h
- include/criterion/internal/assert.h
- include/criterion/internal/common.h
- include/criterion/internal/parameterized.h
- include/criterion/internal/redirect.h
- include/criterion/internal/test.h
- include/criterion/internal/theories.h
- include/criterion/parameterized.h
- include/criterion/redirect.h
- include/criterion/theories.h
- include/criterion/types.h
Thanks to the recent work of @a1lu, we got some proper doxygen generation on the repository.
However, this effectively split the documentation in half, with sphinx on one hand and doxygen on the other.
This PR aims to harmonize both documentations by integrating doxygen comments into the sphinx doc -- the current result can be browsed [here](http://criterion.readthedocs.org/en/features-sphinx-doxygen).
Notable changes are visible on the assertion reference:
| Before | After |
| --- | --- |
[Rendered](http://criterion.readthedocs.org/en/latest/assert.html) | [Rendered](http://criterion.readthedocs.org/en/features-sphinx-doxygen/assert.html)
[Source](https://raw.githubusercontent.com/Snaipe/Criterion/bleeding/doc/assert.rst) | [Source](https://raw.githubusercontent.com/Snaipe/Criterion/featu …
> Integrate doxygen with sphinx docs

- src/log/normal.c
- test/cram/asserts.t
- test/cram/core.t
- test/cram/crashes.t
- test/cram/early-exit.t
- test/cram/fail-fast.t
- test/cram/parameterized.t
- test/cram/pattern.t
- test/cram/redirect.t
- test/cram/suites.t
- test/cram/theories.t
The numbers next to Failing and Crashing in the text synthesis will not be printed red, if they are zero.
> Visibility change:

- src/io/xml.c
This turned out to be a bug in the recent C99 support:
https://connect.microsoft.com/VisualStudio/Feedback/Details/1161593
(ticket probably needs some votes to draw their attention)
Since this is little to no value there for `restrict` anyway, it has
been removed.
> Remove `restrict` keyword usages

- .cmake/Modules/Capabilities.cmake
- CMakeLists.txt
- test/cram/asserts.t
This PR fixes a couple of issues that I encountered when compiling/testing Criterion on a fresh install of FreeBSD 10.3.
The first commit fixes the following build failure:
Linking C shared library libcriterion.so
/usr/bin/ld: cannot find -lanl
Which is caused by libanl (part of glibc) not being available.  Since it is only required by nanomsg for `getaddrinfo_a`, I added a check for that symbol to `.cmake/Modules/Capabilities.cmake` and link when present.  This matches the nanomsg behavior.
The second commit fixes a cram test failure in `test/cram/asserts.t` due to the FreeBSD libc defining `NULL` to `nullptr` rathern than `__null` when compiling as C++.  The test now matches against either keyword.
Thanks for considering,
Kevin
> Compilation and test fixes for FreeBSD

- src/CMakeLists.txt
If `${CMAKE_INSTALL_PREFIX}` is mentioned explicitly in the install() command, the generated `cmake_install.cmake` file will contain a hard-coded value.
This can cause installation errors during debian package generation, since the `cmake -DCMAKE_INSTALL_PREFIX=../debian/tmp/usr -P cmake_install.cmake` command is used in the debian/rules file (this command overrides the original `CMAKE_INSTALL_PREFIX`).
```
$ cmake -DCOMPONENT=Unspecified -DCMAKE_INSTALL_PREFIX=../debian/tmp/usr -P cmake_install.cmake
-- Installing: /home/anno/Criterion/b/Debian/criterion-2.2.1-2.orig/build_dir/../debian/tmp/usr/lib/libcriterion.so.2.2.1
...
-- Installing: /usr/share/pkgconfig/criterion.pc
CMake Error at src/cmake_install.cmake:44 (file):
file INSTALL cannot copy file …
```
> pkgconfig: fix the installation path of criterion.pc

- .gitmodules
- CMakeLists.txt
- include/criterion/options.h
- src/core/abort.c
- src/entry/params.c
- test/cram/help.t
Crash the test if an assert fails so that an debugger can gain control.
signal() and abort() should be portable.
> added --crash cli option (#126)

- include/criterion/abort.h
- src/core/abort.c
Improves PR #139, so that --crash works for cr_expect too.
> improve #139: added --crash for cr_expect ( #126)

- src/entry/params.c
criterion_options.debug was not set if no argument was given. According
to the docs the native debugger should used, so this member has to be
set to CR_DBG_NATIVE.
> fix: set criterion_options.debug to CR_DBG_NATIVE

- src/compat/section-elf.c
- src/core/report.c
- src/core/runner.c
Running a test binary with many tests and/or assertions, such as the following example:
```C
#include <criterion/criterion.h>
Test(suite, test) {
/* Note:  2000 needs to be above current RLIMIT_NOFILE */
for (unsigned int i = 0; i < 2000; ++i) {
cr_assert(1);
}
}
```
on systems with ELF binaries causes the program to abort, usually in `call_report_hooks_*` due to `open_module_self` returning `0` due to `EMFILE` from [`open`](https://github.com/Snaipe/Criterion/blob/c5bfe03/src/compat/section-elf.c#L71).
This PR fixes the issue by calling `close_module` for every successful `open_module_self` call and ensuring that `open_module_self` closes any file descriptors it opens when returning a failure code.
Thanks for considering,
Kevin
> section: Fix "Aborted" due to too many open files

- src/config.h.in
- src/core/runner.c
In my environment I am not allowed to create a UNIX socket in the current working directory (mounted Docker volume).
I think creating the nanomsg socket in /tmp/ or /var/lib/ is a better practice.
> Do not create sockets in current directory

- .cmake/Modules/Subprojects.cmake
cr_add_subproejct didn't work correctly when Criterion was used as a git submoudle in another project as follows.
$ cd my_git_project
$ mkdir vendor
$ git submodule add \
https://github.com/Snaipe/Criterion.git vendor/criterion
You can reproduce the problem by running [a script](https://gist.github.com/MasayukiNagamachi/0fa79ee62ca77a42f2fa1d5e3bac9719).
When you run the script, you can see the following error messages:
```
$ mkdir test
$ sh reproduce.sh test
...
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1915 (message):
No download info given for 'csptr' and its source directory:
/path/to/root/source/dependencies/libcsptr
is not an existing non-empty directory.  Please specify one of:
* SOURCE_DIR with an existing non-empty directory
* URL
* GIT_REPOSITORY
* …
```
> cmake: Replaced CMAKE_CURRENT_SOURCE_DIR with CMAKE_SOURCE_DIR

- doc/debug.rst
'debugging server installed on your server' -> 'debugging server installed on
your machine'. Considered changing the first mention of "server" to "software"
but noticed that the "software" is more often called "server" (gdb, lldb). So I
changed the second "server" instead as a matter of style (also, Criterion won't
always be used in a _server_).
'remote target localhost:1234' -> 'target remote localhost:1234'. The given
command is just wrong and unrecognized by gdb.
> doc: Fix minor errors in debug.rst.

- samples/redirect.cc
- src/io/file.c
When using `cr_file_match_str`, if the provided string we want to match the file against is longer than the contents of the file, the function returns that the file matches the string.
This function is used by many other assertion routines (namely those asserting the contents of the standard output streams). This can be very error-prone when designing tests such as the following:
```c
Test(criterion, cr_file_match_str, .init = cr_redirect_stdout)
{
printf("%s%d%s", "string", 42, "other");
fflush(stdout);
cr_assert_stdout_eq_str("string42othernonsense");
}
```
This commit makes it so that `cr_file_match_str` detects this kind of mismatch.
Note: It does not alter the fact that the function consumes all of the stream.
> Make cr_file_match_str fail if str is longer.

- src/io/file.c
- test/redirect.cc
The following test would not run correctly:
```c
Test(putstr_second, test_outputs, .init = cr_redirect_stdout) {
cr_assert_stdout_eq_str("");
}
```
This is due to the `matches` variable being set to 0 by default. When
the file is empty, the main loop is not run and `matches` never gets the
chance to be updated. The function thus returned that the file and the
string do not match.
A unit tests has been added to prevent further regression.
An `if` statement has also been added before the consuming loop in
`cr_file_match_str` which avoids an unnecessary call to `fread` if we
already know that the stream is empty.
EDIT:
Would it be possible for `ctest` to automatically run this command before executing:
```
cmake --build . --target criterion_tests
```
I've had all the tests failing before I …
> Make `cr_file_match_str` succeed when both file and string are empty.

- appveyor.yml
I'm really sorry, I did break AppVeyor on the `bleeding` branch. 😞 
Many git commands send their output to stderr even if it's not a real error.
PowerShell seems to react fatally to this (NativeCommandError).
> appveyor: checkout quietly

- include/criterion/internal/asprintf-compat.h
- include/criterion/options.h
- src/CMakeLists.txt
- src/compat/path.c
- src/compat/path.h
- src/compat/posix.h
- src/entry/params.c
- src/io/output.c
- test/CMakeLists.txt
- test/path.c
This PR adds directory support to test reports (`CRITERION_OUTPUTS`, `--output`).
The functionality is the same as in GTest (GTEST_OUTPUT):
`--output=PROVIDER:PATH`: Write a test report to `PATH` using the output provider named by `PROVIDER`.
If `PATH` is an existing directory, the report will be created in that directory.
The report file will be named after the binary. For example: test_foo --> test_foo.xml
If the file already exists, Criterion will pick a different name (test_foo_1.xml, test_foo_2.xml) to avoid overwriting it.
----------------------
Adding a dynamically sized string class to Criterion was an enormous overkill, but it made the implementation of `cri_path_gen_unique_filename()` and `cri_path_combine()` much cleaner.
I hope I haven't broken Criterion's KISS principle too …
> Add directory support to test reports

- include/criterion/assert.h
cr_(assert/expect)_mem_(n)eq are implemented by calls to
cr_assert_mem_op_va_. But while the documentation of
cr_(assert/expect)_mem_neq contains the third parameter Size, the
documentation for cr_(assert/expect)_mem_eq does not.
This fix only touches the "declaration" and the documentation of
cr_assert_arr_eq and cr_expect_arr_eq.
> Add missing parameter to the documented interface.

- src/compat/section-elf.c
```
In file included from /tmp/x/Criterion/src/compat/section.c:26:
/tmp/x/Criterion/src/compat/section-elf.c:65:20: error: use of undeclared identifier 'CTL_KERN'
int mib[4] = { CTL_KERN, KERN_PROC, KERN_PROC_PATHNAME, -1 };
^
/tmp/x/Criterion/src/compat/section-elf.c:65:30: error: use of undeclared identifier 'KERN_PROC'
int mib[4] = { CTL_KERN, KERN_PROC, KERN_PROC_PATHNAME, -1 };
^
/tmp/x/Criterion/src/compat/section-elf.c:65:41: error: use of undeclared identifier 'KERN_PROC_PATHNAME'
int mib[4] = { CTL_KERN, KERN_PROC, KERN_PROC_PATHNAME, -1 };
^
/tmp/x/Criterion/src/compat/section-elf.c:67:5: warning: implicit declaration of function 'sysctl' is invalid in C99 [-Wimplicit-function-declaration]
sysctl(mib, sizeof (mib) / sizeof (int), self, &cb, NULL, 0);
^
1 warning and 3 errors …
```
> Fix build on FreeBSD

- src/entry/params.c
- test/cram/help.t
The usage now displays information about the `--json` flag.
Before, no information about the `--json` flag was mentioned in the criterion program's usage.
> Addition of JSON flag in the program's usage

- src/io/file.c
With each iteration of the loop, `match` was unconditionally reassigned
to whatever the return of `!memcmp(buf1, buf2, read1)` was. This causes
the result of comparing previous blocks to be overwritten without being
checked.
This PR exits the loop early as soon as a difference is found.
This case isn't trivial to test since it requires files larger than a
block (512o) to be matched. I have tested it locally by manually setting
the buffer sizes to 2 and with smaller files.
I don't know how to add tests for it alongside existing tests in this
project but would gladly do it if provided guidance.
> io: fix cr_file_match_file matching only the last block.

- doc/parameterized.rst
This seems like a documentation bug. I cannot see how this can be correct in its current form.
> Struct pointer references use -> instead of dot

- dev/autotools/autogen.sh
This location depends on the initial install directory of automake. Eg, it can be installed inside /usr/local instead of /usr
> Update the share directory location

- meson.build
- src/meson.build
> ci: Fixed paths to isdir.py and dependencies when building as meson subproject

- include/criterion/internal/asprintf-compat.h
- include/criterion/internal/assert/op.h
- include/criterion/internal/assert/tag.h
- include/criterion/internal/assert/tostr.h
- include/criterion/internal/common.h
- src/core/client.c
- src/entry/params.c
- src/io/json.c
- src/io/tap.c
- src/io/xml.c
- src/meson.build
MinGW uses by default the windows CRT for printf, but can be convinced
to use its own ANSI-compatible printf implementation by defining the
__USE_MINGW_ANSI_STDIO macro.
This fix is two-fold: first, we use the "I64" specifier prefix instead of "ll"
for the long long type modifier if we're using MSVC.
Then, since cr_asprintf uses printf and is compiled in libcriterion.so,
we have to make a choice on which printf to use for our users.
Naturally, we prefer the standards-compliant one.
Fixes #322.
> api: use the correct printf specifiers on mingw-gcc.

- src/meson.build
I've noticed on recent builds that meson warnings crept in. This fixes them.
> meson: fixed warnings.

- src/compat/section-elf.c
On some architectures, it's possible to make the kernel use 64KiB pages.
We've had some code in the elf section handling that aligned sections on
4KiB page boundaries regardless, instead of asking for the right page
size through sysconf(3).
Fixes #289.
> elf: stop assuming that PAGE_SIZE is 4KiB.

- meson.build
- meson_options.txt
tl;dr same as https://github.com/Snaipe/BoxFort/pull/27 but for Criterion.
When using Criterion as a subproject, meson test runs Criiterion's tests. I believe a typical developer developing their super project wants to run only own tests, not dependencies' ones.
This PR adds -Dsamples and -Dtests options to enable/disable, like this:
```sh
meson setup -Dsamples=false -Dtests=false build && cd build && meson test
meson setup -Dcriterion:samples=false -Dcriterion:tests=false build && cd build && meson test
```
> meson: Add options to not-build samples and tests.

- include/criterion/internal/assert/op.hxx
- include/criterion/new/assert.h
- test/cram/asserts.t
- test/full/failmessages.c
- test/full/failmessages.cc
We also stop using empty() and ! as a basis for checking for zero-ness,
and instead we simply compare the current parameter with the zero value
of the type. This does requires that the type is default-constructible,
which is, I think, reasonable, because a type that does not have
a default-constructor cannot be guantanteed to define what a
"zero-value" of itself means, if any.
It is probably fine to make that assumption and document it as such, as
the obvious workaround is to cr_assert the appropriate boolean
condition.
> api: fixed zero producing warnings for primitive types in C++.

- meson.build
- meson_options.txt
- src/meson.build
- src/string/diff-stubs.c
Added the meson option to disable dependency of `libgit2`.
My use case is:
- I try to produce a minimal `Dockerfile` for my software and I am on very early stages. In the end it will be used in CI;
- I use Criterion :) ;
- `libgit2` is a big library which adds both to `docker build` time and taking space, and all it brings is to diff strings in 2 places (`src/core/assert.c` + `src/log/normal.c` via `cri_diff_buffer_to_buffer`).
- Right now it is good enough for me to not-have beautiful git-diffs. I still get the failed assertion anyway and I can get proper git-diff running the test locally. :)
> meson: add option to disable libgit2

- include/criterion/alloc.h
The `std::allocator<T>` type in the C++ standard library does not declare
the `const_pointer` associated type anymore, as per the update of the
C++ standard.
This fix replaces its usage with a normal constant pointer:
```diff
-typename std::allocator<void>::const_pointer
+const std::allocator<void>::value_type *
```
> Fix C++20 compatibility: Removed feature used

- src/string/brz.c
There is a small typo in src/string/brz.c.
Should read `character` rather than `chacacter`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, chacacter -> character

- dev/autotools/Makefile.am
- dev/autotools/README.md
- dev/autotools/autogen.sh
- dev/autotools/configure.ac
I have been helping students setup a big project using Autotools and Criterion at my school. Having used both of them together before, I was surprised to see that your example setup is way more complicated than what I had arrived at by reading the documentation.
I have both simplified the setup to use environment variables to setup TAP output (making the use of a wrapper shell script redundant), and made the example stricter in terms of good practices regarding the use of Autotools.
> Simplify autotools example

- src/io/xml.c
- test/cram/xml.t
The current xml writer produces incorrect xml files when using `cr_assert_lt` or `cr_assert_gt`. Special characters like `>`, `<`, `&` were not escaped.
Enclosing the error messages in a CDATA section allows us to not have to escape such characters and keep the XML human readable.
> xml: Fix escape of special characters

- src/log/normal.c
Fixes #311.
The issue was caused by an unchecked dereferencing of the first token
returned by `strtok_r()`, which is NULL if the message is empty.
> log: Fix crash in `cr_log_info()` on empty string

- src/compat/section-mach-o.c
Criterion/src/compat/section-mach-o.c:98:9: error: implicit declaration of function 'cr_panic' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
cr_panic("Could not allocate cri_section");
^
1 error generated.
Fixes #392
> fix: compile error on macOS Monterey

- subprojects/boxfort.wrap
Depends on Snaipe/BoxFort#33
Fixes #312
Fixes #376
> Fix non-deterministic crash on aarch64, support Apple silicon

- README.md
- doc/intro.rst
- doc/setup.rst
- rename OS X to macOS
- update Ubuntu/Debian installation steps (official .deb packages: https://repology.org/project/criterion/versions)
- document that libffi (and other build dependencies) needs to be installed when compiling from source
- replace dyncall reference with libffi
- replace old macOS brew repo with `mranno/tap/criterion`, which has binary packages compiled from the current `bleeding` branch.
Resolves #372
Fixes #391
> Docs update

- .cirrus.yml
As explained in #319, I left out the ARM builds because there were non-trivial failures.
To be more precise, exception handling is plainly broken -- criterion doesn't catch anything at all.
Let's figure out why and fix that in this PR.
> ci: add ARM and AArch64 builds

- include/criterion/internal/assert/tostr.h
- samples/asserts.cc
- test/cram/asserts.t
- test/full/failmessages.cc
This piece of SFINAE hair-pull adds support for printing STL containers (and for that matter, all iterables), which enables their direct use in all criteria.
Fixes #331.
> api,asserts: add support for iterables

- include/criterion/internal/test.h
Fixes #222. The other warning was fixed in an earlier commit.
> api,misc: remove redundant cri_asserts_passed_incr declaration

- test/cram/meson.build
This restores the ability to patch cram failures via `CRAM=-iy ninja test`,
which broke when switching to meson: because the test directory passed
to cram was an absolute path, the patch program would also get fed absolute
path, which in turn declined to do anything for safety reasons.
This commit forces the cram test to execute with the working directory
set to the project root, passing `test/cram` as path instead.
Interestingly, changing the workdir to test/cram and then using `.` as
test path did not work.
> misc,cram: fix cram patch not working from ninja test

- include/criterion/internal/assert/ieee.h
- samples/asserts.c
> api,float: fix ULP comparison when threshold is 0, and comparing infinities with epsilons.

- include/criterion/internal/assert/tostr.h
- test/cram/asserts.t
- test/full/failmessages.cc
- test/unit/asprintf.c
This is a fix for something that was introduced in #405, so no changelog entry is needed.
@Snaipe
The PR is opened against `bleeding`, but we are in the middle of a release. Which workflow do you prefer? Should I change the base to `master` and then merge that branch back into `bleeding`?
> Fix build with older gcc versions

- .github/workflows/ff-bleeding.yml
- .github/workflows/release.yml
- meson.build
- src/meson.build
This PR tries to automate the last few steps of the Criterion release process.
When a commit is pushed to the master branch or a version tag is created, the release workflow starts automatically.
The workflow can be restarted manually on either a tag or a branch if needed.
The release draft workflow creates the source tarball (which includes all subprojects), builds Criterion from the tarball, and creates binary packages.
Binary packages are created within a CentOS 7 container. This sounds terrible, but it ensures that Criterion is built with an older glibc version (v2.17) so that it will work on a wide variety of Linux distros.
The source tarball and the binaries then will be attached to the release on the Releases page.
In case new commits are pushed to the master branch, a pre-release …
> Automated release workflow

- .gitmodules
- ChangeLog
- doc/debug.rst
- src/core/runner_coroutine.c
- subprojects/boxfort.wrap
- `--debug` now uses the official macOS `debugserver` by default (if it's on `PATH`)
- `--debug` will fall back to the `idle` method in case no debugger can be found
Depends on Snaipe/BoxFort#36
Fixes #420
> Fix debugging on macOS and add fallback debug method

- subprojects/boxfort.wrap
Fixes #424
See also #364
Depends on Snaipe/BoxFort#38
Note: I've added `[skip actions]` to the commit message just in case we want to skip creating another release candidate.
IMHO no changelog entry is needed, `Fix: worked around msync not properly working on WSL and causing the runner to break` covers this PR as well.
> Workaround for unimplemented mincore() on WSL 1

- include/criterion/internal/assert/op.h
- include/criterion/internal/assert/tag.h
- include/criterion/internal/new_asserts.h
- src/capi/stream.c
- src/compat/processor.c
- src/compat/section-elf.c
Fixes #446.
There are ~160 warnings in Criterion related to implicit conversions.
I haven't fixed all of them as most seemed to be false positives.
This PR focuses on user-facing ones and a few others.
> Fix user-facing compiler warnings with `-Wconversion`

- README.md
FreeBSD package is now available.
Port [commit information](https://cgit.freebsd.org/ports/commit/?id=c32decee33ce9db095fb2b77e4ece07c5ec50f59).
FreshPorts [information](https://www.freshports.org/devel/criterion/).
> Add FreeBSD package information to README

- src/core/client.c
- test/cram/asserts.t
- test/cram/bugs.t
- test/full/bug463.c
- test/full/meson.build
If the user-provided function to stringify an object is bugged and produces equal output for non-equal objects, thus producing an empty diff, Criterion would crash trying to access an unset parameter list.
This fixes the crash by checking that we do have expected values, and printing placeholder messages if we do not.
Fixes #463.
> diff: fix crash in assert failure reporting when there is no diff

- src/protocol/gen-pb.py
In gen-pb.py, we call protoc to compile our protobuf declarations with nanopb's generator plugin.  The issue is that we used a space between -f and the name of the option file, which causes the option file to not be found as the space is considered part of the filename.
If the option file is not found, all our unit tests crash on Debian testing, with nanopb 0.4.7.  Earlier versions of nanopb probably were not so picky about that space.
Signed-off-by: Balazs Scheidler <bazsi77@gmail.com>
> nanopb: fix incorrect arguments to protoc

- src/core/client.c
- src/core/client.h
- src/core/runner.c
Root cause: `client_ctx::alive` handling and BoxFort timeout conflict
To indicate that a client is dead, a death message has to be sent to the runner, and that message needs to be the very last message. This is done correctly.
The problem is `handle_birth()`, which sets the `alive` flag to true. Under rare circumstances (overloaded system), the `handle_birth()` action may never run due to the test timeout that occurs before sending out the birth message. This scenario leaves the `alive` flag on false, causing a deadlock:
```
-- thread 1
run_tests_async():
while (read_message()):
process_message()
if not alive -> remove_client() -> destroy_client_context() -> bxf_wait() -> pthread_cond_wait()
-- thread 2
child_pump_fn():
reap_child() -> death_callback() -> cr_send_to_runner() * 2 -> …
```
> core: fix deadlock in overloaded scenarios

- src/core/client.c
Quick fix for a memory leak on test failure.
> client: Free duplicated message on test failure

- include/criterion/internal/assert/op.h
- samples/asserts.c
- samples/asserts.cc
- test/cram/asserts.t
Before this patch, the following assert was true:
`cr_assert(gt(int,0,0));`
Fixes #473
> Fix gt() and ge()

- README.md
`nix-env` for installing packages is a bad habit for nix/NixOS users and it is not recommended from the community as it doesn't mix well user configuration.nix / flake and/or home-manager. It also alters the system rather than providing a temporary package.
Since this is within the `download` section, it would make sense to use `nix-shell criterion` which will create a sub-shell with environment variable set to have criterion available.
I would have personally used `nix shell nixpkgs#criterion`, but the `nix` command is still an experimental feature, and isn't enabled by default
> Use `nix-shell` instead of of `nix-env -iA`

- README.md
Keep readme sync with `subprojects/debugbreak.wrap` file, which has it's URL set to MrAnno's fork.
> Replace debugbreak repo to MrAnno's fork

- doc/env.rst
JSON and XML outputs were using the TAP example as output. This PR fixes the reference to the appropriate example.
> docs: Fix references to JSON/XML output format

- ci/isdir.py
- meson.build
Solves the problem mentioned in #543 where the `meson.build` file would base its dynamically generated version string off the root project git repository state if it was added to a project as a git submodule or a meson wrap file.
> meson.build: ensure the project git directory is used

- doc/setup.rst
This fixes [missing build commands](https://criterion.readthedocs.io/en/master/setup.html#building-from-source) in the Read the Docs documentation caused by a missing blank line before a code block.
> docs: Fix code block in setup doc

- include/criterion/theories.h
This PR adds a clarification into the docs for theory data points, specifying
that the size of the given type for a data point must not exceed
sizeof(uint64_t), as Criterion only supports types with sizes up to that limit.
Intended to solve issue #567
> docs: Add clarification on allowed types for theory data points.
